### ISSUE TITLE
Less strict expectEvent

### ISSUE THREAD

**Issue by alejoamiras** [OpenZeppelin/openzeppelin-test-helpers#102]
Hey there ! 
I was working in some unit tests for a SC, and thought that it would be awesome to add the option to be less strict in the args argument of the expectEvent. Let me explain why.

**Setup**
```
contract A {
   funct emitFirstEvent() {
       emit FirstEvent(args);
  }
}

contract B {
  funct secondFunction () {
     A.emitFirstEvent();
     emit SecondEvent(args);
  }
}
```
**Logic**
Let's say I'm testing my contract **B**. I'd like to test that A emitted **firstEvent**, but I don't really want to test if the args where emitted correctly, that's up to the unit tests of the A contract. 

In case you agree that it would be cool to have this feature. Any suggestions on how you'd like to see this implemented ? I thought about making `eventArgs = {}` in `expectEvent (receipt, eventName, eventArgs = {})` optional, but it may be misleading.

**Comment by frangio** [comment]
Hi @alejoamiras!

If I understand the request correctly, I think we already provide this feature. `eventArgs` is an optional argument. [Take a look at the docs.](https://github.com/OpenZeppelin/openzeppelin-test-helpers/blob/5651e756311188849ff6c22e3746a2b33be45b56/README.md#expectevent-receipt-eventname-eventargs--) The documentation is not clear on what that implies though. We should improve that.

**Comment by frangio** [comment]
If you don't specify event arguments it will only check for the existence of an event with the given name.

In general, it will only validate the event arguments that you do specifiy. (Therefore, if you don't specify any, it won't validate them at all.) This is more or less what the docs should say.

**Comment by nventuro** [comment]
Hm, indeed: the only indication of `eventArgs` being optional is the function signature, a detail which can be easily missed.

We've intentionally kept the documentation short since it all has to fit in the readme: once we switch to the main documentation site (https://docs.openzeppelin.com) this should be an easy fix.
