### ISSUE TITLE
Use Test Environment

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-test-helpers#118]
It would be nice to change the setup in this project to use [OpenZeppelin Test Environment](https://github.com/OpenZeppelin/openzeppelin-test-environment).

**Comment by nventuro** [comment]
An issue is that Test Environment will load the helpers and configure them, which is I think why I left these with truffle.

**Comment by frangio** [comment]
That's interesting. Maybe it should be possible to configure Test Env to skip that?

**Comment by frangio** [comment]
Not worth changing this.
