### ISSUE TITLE
expectEvent.not for Truffle receipt

### ISSUE THREAD

**Issue by AuHau** [OpenZeppelin/openzeppelin-test-helpers#120]
I discovered "not" versions for `inConstruction` and `inTransaction`, yet there is no "not" for the original `expectEvent`. 

I guess you can work-around that with `expectEvent.not.inTransaction(receipt.tx, 'Event')` but that is not really elegant.

Am I missing something or can I create PR with this addition?

**Comment by frangio** [comment]
It was an oversight. We would like to have a function that receives a receipt rather than a transaction, just like `expectEvent`. It has to work with both Truffle and Web3 receipts too. You can go ahead and create a PR!

**Comment by AuHau** [comment]
Awesome!

Quick question, what should be API? 

 - `expectEvent.not(receipt, event)`
 - `expectEvent.not.include(receipt, event)`
 - something else?

**Comment by frangio** [comment]
I think this is a helper for which we haven't found a good name yet. Perhaps we should go with `expectEvent.notEmitted(receipt, event)`. In any case, you can open a PR and we can work out the name later.
