### ISSUE TITLE
Web3 method to pull a "receipt" for expectEvent from a contract I don't call directly?

### ISSUE THREAD

**Issue by zach-is-my-name** [OpenZeppelin/openzeppelin-test-helpers#139]
_Edit: tx hash not available_ 
I have a set up where I need to grab the "receipt" from `Contract B` called indirectly from Service, in order to properly test `Contract A`.  

I thought I successfully found a web3 method that returns data that expectEvent()  can consume, although I forget which one, either `Contract.getPastEvent()` or `web3.eth.getPastLogs()` or something else... any direction would be much appreciated

**Comment by zach-is-my-name** [comment]
Solved: 
```
   const events = web3.eth.Contract().getPastEvents() (Promise returns Array of events) 
   expectEvent(events[i])
```

**Comment by frangio** [comment]
I would recommend using `getPastEvents` and looking through the array manually. `expectEvent` is specifically designed for working with tx hashes and receipts.
