### ISSUE TITLE
Expect Event: Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by zach-is-my-name** [OpenZeppelin/openzeppelin-test-helpers#140]
Is this being caused by `expectEvent()` ? I went as crazy as I could with the `.catch()` statements but still coming up short 
(I know I'm `await`ing  `expectEvent()` that is synchronous, but while throwing everything at the wall I figured it  didn't matter)
![Screenshot from 2020-11-08 01-18-52](https://user-images.githubusercontent.com/16063092/98458668-1272f480-2161-11eb-9a91-b141ff41841b.png)
![Screenshot from 2020-11-08 01-21-40](https://user-images.githubusercontent.com/16063092/98458669-14d54e80-2161-11eb-9682-d491a2f764af.png)

**Comment by frangio** [comment]
Hi @zach-is-my-name. Sorry it took a while to reply to this. We have faster response times at [forum.openzeppelin.com](https://forum.openzeppelin.com/).

You seem to be using `expectEvent` in the wrong way. The first argument should be a transaction receipt, from a contract function call. Take a look at [the documentation](https://docs.openzeppelin.com/test-helpers/0.5/api#expect-event).

Using `expectEvent` together with `getPastEvents` is not possible. It may be possible to add it as a new feature but we haven't generally seen the need for it.

**Comment by zach-is-my-name** [comment]
Thanks, this relates to #139 which I opened.  Although, I've had some success using `getPastEvents()` it's still unreliable for me

**Comment by frangio** [comment]
For your issue #139 I would recommend using `getPastEvents` and looking through the array manually. `expectEvent` is specifically designed for working with tx hashes and receipts.
