### ISSUE TITLE
"If your node does support revert reasons, please let us know"

### ISSUE THREAD

**Issue by alsco77** [OpenZeppelin/openzeppelin-test-helpers#144]
## What

When using `expectRevert` with a message, the below warning appears

```
@openzeppelin/test-helpers WARN expectRevert: Assertions may yield false negatives!

Revert reason checks are only known to work on Ganache >=2.2.0, and the current node is HardhatNetwork/2.0.3/ethereumjs-vm/4.2.0.

If your node does support revert reasons, please let us know: https://github.com/OpenZeppelin/openzeppelin-test-helpers/issues/new
```

## Supported

The [Hardhat EVM](https://github.com/nomiclabs/hardhat) supports revert reasons (`HardhatNetwork/2.0.3/ethereumjs-vm/4.2.0`) and should be whitelisted

**Comment by frangio** [comment]
@alsco77 Hardhat was whitelisted in #131. Can you check if you're using the latest version of test-helpers?

**Comment by alsco77** [comment]
Woops - my bad, i'm on an old version. Sorry @frangio !
