### ISSUE TITLE
TypeError: We.singletons.ERC1820Registry is not a function

### ISSUE THREAD

**Issue by olegabr** [OpenZeppelin/openzeppelin-test-helpers#148]
`TypeError: We.singletons.ERC1820Registry is not a function`

After update from `"@openzeppelin/test-helpers": "^0.5.3",` to `"@openzeppelin/test-helpers": "^0.5.9",`

```
import { singletons } from '@openzeppelin/test-helpers'
const registry = await singletons.ERC1820Registry("0x0000000000000000000000000000000000000000")
```

webpack is used to build.

reverted back to `0.5.3` for now

**Comment by olegabr** [comment]
It is not version dependent. looks like it is a webpack issue. webpack build errors:

```
ERROR in ./node_modules/fs-extra/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/home/USER/PROJECTDIR/node_modules/fs-extra/lib'
 @ ./node_modules/fs-extra/lib/index.js 23:11-24
 @ ./node_modules/@openzeppelin/contract-loader/lib/index.js
 @ ./node_modules/@openzeppelin/test-helpers/src/singletons.js
 @ ./node_modules/@openzeppelin/test-helpers/index.js
 @ ./js/hooks/useIsTokenERC777.js
```

**Comment by frangio** [comment]
This looks like a Webpack configuration problem. You may be bundling for the browser, where the `fs` module is not available, which is used indirectly in our singletons module to read from disk. This library is not designed for use in the browser unfortunately.
