### ISSUE TITLE
AvalancheGO

### ISSUE THREAD

**Issue by echocharlie125** [OpenZeppelin/openzeppelin-test-helpers#153]
I've got following messages using local AvalancheGO network (avsh) : 

@openzeppelin/test-helpers WARN expectRevert: Assertions may yield false negatives!

Revert reason checks are only known to work on Ganache >=2.2.0, and the current node is coreth-v0.3.23.

If your node does support revert reasons, please let us know: https://github.com/OpenZeppelin/openzeppelin-test-helpers/issues/new

**Comment by abcoathup** [comment]
Hi @echocharlie125!  

Thanks for the suggestion, it is really appreciated.

Does Avalanche Go support revert reasons?

Once we have more information, the project owner will then review your suggestion as soon as they can.  

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by echocharlie125** [comment]
Hi Andrew,,
Thanks for your reply. I am not a contributor to the Avalanche Project. Any idea i can "check" if AvalancheGo supports revert reasons ?

**Comment by frangio** [comment]
@echocharlie125 You can trigger a revert with revert reason in the console and show us the output. We need to see the error message.

**Comment by israel-gonzalezmedina** [comment]
I have the same problem @frangio and @abcoathup 
here is my output:
      Wrong kind of exception received
      + expected - actual

      -Transaction: 0xf4219d9d6e0dc92efd666b98265222361ce8adb9146f6ffbb64907cf25446e60 exited with an error (status 0). 
      -     Please check that the transaction:
      -     - satisfies all conditions set by Solidity `require` statements.
      -     - does not trigger a Solidity `revert` statement.
      +ERC20PresetMinterPauser: must have minter role to mint

**Comment by frangio** [comment]
That doesn't look like the same problem.
