### ISSUE TITLE
Testing Refundable Crowdsale

### ISSUE THREAD

**Issue by AhmedAwadallah257** [OpenZeppelin/openzeppelin-test-helpers#157]
I'm trying to call the below contract in the test file:

`const RefundEscrow = artifacts.require('./RefundEscrow');`

But I get the following error:

`Error: Could not find artifacts for ./RefundEscrow from any sources`

Noting that the RefundEscrow.sol file is exist in @openzeppelin\contracts\payment\escrow

**Comment by abcoathup** [comment]
Hi @AhmedAwadallah257,

I see that you are discussing this in the forum with a community member: https://forum.openzeppelin.com/t/artifacts-require-refundescrow/6784
I will close this issue.
