### ISSUE TITLE
expectRevert returns Error: Invalid JSON RPC response: "" in hardhat framework

### ISSUE THREAD

**Issue by gfijrb** [OpenZeppelin/openzeppelin-test-helpers#176]
Expected result:
Test should be passed

Received result:
Error: Invalid JSON RPC response: ""

**Configs and logs:**

Hardhat config file
```json
{
  "name": "@alium-finance/shp-v2",
  "license": "MIT",
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-etherscan": "^2.1.7",
    "@nomiclabs/hardhat-solhint": "^2.0.0",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@nomiclabs/hardhat-web3": "^2.0.0",
    "@openzeppelin/test-helpers": "^0.5.15",
    "@typechain/ethers-v5": "^7.2.0",
    "@typechain/hardhat": "^2.3.1",
    "@types/mocha": "^9.0.0",
    "chai": "^4.3.4",
    "dotenv": "^10.0.0",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.4.4",
    "hardhat": "^2.6.0",
    "hardhat-abi-exporter": "^2.3.1",
    "hardhat-gas-reporter": "^1.0.4",
    "solidity-coverage": "^0.7.17",
    "ts-node": "^10.1.0",
    "typechain": "^6.0.4",
    "typescript": "^4.3.5",
    "web3-eth-contract": "^1.6.1"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^4.2.0"
  },
  "scripts": {
    "build": "npx hardhat compile",
    "test": "npx hardhat test",
    "dist": "npx waffle flatten"
  }
}
```

Log screen
```
$ yarn test
yarn run v1.22.15
$ npx hardhat test
No need to generate any newer typings.


  StrongHolderPool
    General
      ✓ #activate (50ms)
      1) #leave


  1 passing (973ms)
  1 failing

  1) StrongHolderPool
       General
         #leave:
     Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (node_modules/@openzeppelin/test-helpers/node_modules/web3-core-helpers/lib/errors.js:43:16)
      at XMLHttpRequest.request.onreadystatechange (node_modules/@openzeppelin/test-helpers/node_modules/web3-providers-http/lib/index.js:95:32)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
      at XMLHttpRequest._setReadyState (node_modules/xhr2-cookies/xml-http-request.ts:219:8)
      at XMLHttpRequest._onHttpRequestError (node_modules/xhr2-cookies/xml-http-request.ts:379:8)
      at ClientRequest.<anonymous> (node_modules/xhr2-cookies/xml-http-request.ts:266:37)
      at ClientRequest.emit (domain.js:470:12)
      at Socket.socketErrorListener (_http_client.js:475:9)
      at Socket.emit (domain.js:470:12)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)



error Command failed with exit code 1.
```

**Comment by frangio** [comment]
This is not the Hardhat config file, it's the `package.json`. Can you share the actual config file?

**Comment by unibeck** [comment]
I am having the same issue

**Comment by soccerarena** [comment]
Same issue here.

**Comment by soroosh123rf** [comment]
Same issue here.

**Comment by soroosh123rf** [comment]
My **hardhat.config.ts** file:

`import * as dotenv from "dotenv";

import { HardhatUserConfig, task } from "hardhat/config";
import "@nomiclabs/hardhat-etherscan";
import "@nomiclabs/hardhat-waffle";
import "@typechain/hardhat";
import "hardhat-gas-reporter";
import "solidity-coverage";

dotenv.config();

// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.9",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },
  networks: {
    mainnet: {
      url: `https://eth-mainnet.alchemyapi.io/v2/${process.env.MAINNET_ALCHEMY_API_KEY}`,
      accounts: [`${process.env.MAINNET_PRIVATE_KEY}`],
    },
    rinkeby: {
      url: `https://eth-rinkeby.alchemyapi.io/v2/${process.env.RINKEBY_ALCHEMY_API_KEY}`,
      accounts: [`${process.env.RINKEBY_PRIVATE_KEY}`],
    },
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY,
  },
};

export default config;
`

**Comment by frangio** [comment]
Thank you for sharing @soroosh123rf. I'm assuming this was the error people were experiencing.

The fact that hardhat-web3 is needed is explained in the installation instructions in the [readme](https://github.com/OpenZeppelin/openzeppelin-test-helpers#hardhat-formerly-buidler).
