### ISSUE TITLE
Figure out what to do with web3

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-test-helpers#2]
Do we want to promisify the current web3 provider and export that? How will this affect people using web3 1.x? 

Also, we can't have people running `const { web3 } = require('openzeppelin-test-helpers')`, since that will clash with their own `web3` instance.

**Comment by frangio** [comment]
Can you explain in more detail what the problem is?

**Comment by nventuro** [comment]
The issue is that our users may be using truffle 5.x, which comes with web3 1.x, which is _very_ different: it uses bn.js instead of bignumber.js, and has a promisifed API instead of a callback-based one. Both of these features are used by the helpers themselves.

**Comment by nventuro** [comment]
With truffle 5 out and upgrading to web3 1.0, and web3 1.0 'committing' to their current API, I don't think the added effort of supporting web3 0.2.x is worth it, so we'll just go with 1.0.
