### ISSUE TITLE
Making chai a dependency

### ISSUE THREAD

**Issue by startgeek** [OpenZeppelin/openzeppelin-test-helpers#32]
hey everyone what's up
it's kind of surprising for me too since truffle should come with chai natively but I guess it only has it in form of internal use and doesn't provide it to external modules such as openzeppelin-test-helper
missing chai dependency and when I npm install it manually it fixes here's a snapshot
![chai ](https://user-images.githubusercontent.com/18519287/56932660-d2599d00-6af9-11e9-871d-e39036fd2e9e.png)

**Comment by frangio** [comment]
Thanks for reporting @startgeek! Funny, @nventuro and I were talking about this exact thing earlier today.

Actually chai is a peer dependency of this package. The reason we made it that way is that we wanted to make sure to be using exactly the same version of chai that the user of this package is using. However... I don't think this is a problem anymore after #18. We might be able to make it an actual dependency now, and the user experience will be _a lot_ better. @nventuro What do you think?

**Comment by nventuro** [comment]
Hm, yes, I'm not sure why I made it a peer dependency on that peer, having a regular dependency makes sense. We should fix this for v0.4.

**Comment by startgeek** [comment]
I believe one step that could be taken before each commit is that I (as a developer ) make a clean fresh environment (probably on VMWARE) with truffle wired and a bunch of heavy contracts and test and before each commit, I could do:
1. truffle init
2.copy contracts and test files
3.npm install openzeppelin-solidity
4.npm install openzeppelin-test-helpers
5.truffle test
and it should pass all of the test's 
this way we could be sure that it doesn't access chai from a global npm repo(which I installed globally once by accident)

**Comment by startgeek** [comment]
oh and I have this question how I can use openzeppelin-test-helpers in migration files?
is it a good idea?
we should consider making another library just for this purpose

**Comment by frangio** [comment]
@startgeek That's a bit unrelated to this issue, it sounds more like the kind of thing to discuss in the forum. :slightly_smiling_face: https://forum.zeppelin.solutions

**Comment by frangio** [comment]
Hm, actually we still need chai as a peer dependency for this to work:

https://github.com/OpenZeppelin/openzeppelin-test-helpers/blob/8a2de4215e7cf2568e56f4cfe8868c636e79a625/src/setup.js#L1-L4

I'm willing to let go of this last bit of magic setup. I think it would be much better if we were completely agnostic to chai. :slightly_smiling_face:

**Comment by nventuro** [comment]
Wouldn't `chai-bn` also become a peer-dependency in that case too?

@startgeek 
>I believe one step that could be taken before each commit is that I (as a developer ) make a clean fresh environment (probably on VMWARE) with truffle wired and a bunch of heavy contracts and test and before each commit, I could do:
    truffle init
    2.copy contracts and test files
    3.npm install openzeppelin-solidity
    4.npm install openzeppelin-test-helpers
    5.truffle test
    and it should pass all of the test's
    this way we could be sure that it doesn't access chai from a global npm repo(which I installed globally once by accident)

We actually already do this :) I've set up a couple [integration tests](https://github.com/OpenZeppelin/openzeppelin-test-helpers/tree/master/test-integration), and as you can see, they have `chai` as an explicit dependency.

**Comment by startgeek** [comment]
> We actually already do this :) I've set up a couple [integration tests](https://github.com/OpenZeppelin/openzeppelin-test-helpers/tree/master/test-integration), and as you can see, they have `chai` as an explicit dependency.

so why I take chai is not defined error in fresh setup?

**Comment by frangio** [comment]
>Wouldn't chai-bn also become a peer-dependency in that case too?

No, we can use it internally without forcing users of test-helpers to use it too.

**Comment by nventuro** [comment]
@frangio we should make a decision about this for the v0.4 release.

**Comment by frangio** [comment]
Do we want to remove auto installation of chai-bn?

**Comment by nventuro** [comment]
I'd rather keep boilerplate to a minimum, and `chai-bn` is IMO too magical for a non-js expert (which is often the case nowadays in the industry): I think it'd be best if we simply hide it from our users.

**Comment by frangio** [comment]
Then we can make chai a dependency of test-helpers in order to use it internally (do we even need it anyway?) and additionally if chai is installed next to test-helpers, register the chai-bn plugin into it.

**Comment by jamesmorgan** [comment]
I just stumbled upon this when using the latest test helpers. Seem strange to have to install both `chai` and `chai-bn` separately, especially since no docs I could find point this out.

**Comment by frangio** [comment]
@jamesmorgan While I agree that it's annoying to have to install `chai`, it _is_ specified as a peer dependency:

https://github.com/OpenZeppelin/openzeppelin-test-helpers/blob/4fa2d9e92c97aaad21218913a1a63f42c05e5ab7/package.json#L57-L59

This should be enough but npm isn't loud enough about these. We are missing documenting this more clearly, but I'd much rather we removed the peer dependency entirely.

`chai-bn` I don't think you should be installing manually, it's a dependency of openzeppelin-test-helpers.

**Comment by nventuro** [comment]
The docs now indicate that `chai` should be installed, and we haven't received any reports related to this recently. Closing.

**Comment by frangio** [comment]
It's still bad UX that users have to install chai manually, due to test-helpers using it internally.

**Comment by VanijaDev** [comment]
Hi, strange but I still get Error: Cannot find module 'chai'
<img width="1271" alt="Screenshot 2019-10-16 at 17 03 07" src="https://user-images.githubusercontent.com/15075510/66926832-616e5900-f037-11e9-99ec-07975368cb5b.png">

**Comment by frangio** [comment]
Thank you for reporting @VanijaDev! No, it's not strange. I implemented it wrong and didn't test it correctly. :man_facepalming:

I'm preparing a fix and will publish it in a short while.

**Comment by frangio** [comment]
@VanijaDev v0.5.3 has been released with the fix.
