### ISSUE TITLE
Improve expectRevert output

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-test-helpers#33]
`chai` includes an (afaik) mandatory message when `include` fails, which causes the actual error log to contain the expected message twice, and be generally very confusing.

This is what you get when a test expects 'ERC777: token recipient contract has no implementer for ERC777TokensRecipient' but gets 'SafeMath: subtraction overflow':

```
AssertionError: Wrong failure type, expected 'ERC777: token recipient contract has no implementer for ERC777TokensRecipient': expected 'Returned error: VM Exception while processing transaction: revert SafeMath: subtraction overflow -- Reason given: SafeMath: subtraction overflow.' to include 'ERC777: token recipient contract has no implementer for ERC777TokensRecipient'
```

We should either opt-out of this `chai` behavior, or write a custom test function.

**Comment by frangio** [comment]
Reopening since #43 was merged prematurely.

The error message still looks bad:

`Error: Wrong failure type, expected 'Wrong reason' and got 'Returned error: VM Exception while processing transaction: revert Call to revert'`

IMO we should show only the revert reasons: expected and actual. The whole `Returned error: VM Exception while processing transaction: revert` thing is just noise.

What I think we sould do is remove the substring `"Returned error: VM Exception while processing transaction: revert "` if it is contained. The exact string could change between versions though. We'll have to keep an eye out for that.

**Comment by frangio** [comment]
We should also be using `AssertionError` instead of plain `Error`. This is accomplished by using [`assert.fail`](https://nodejs.org/api/assert.html#assert_assert_fail_message).

**Comment by itinance** [comment]
I'm confused now. Just upgraded to 0.4.0 and changed all occurences of `shouldFail` to expectRevert, which breaks my tests.
Did I missed something here or is it a good advice to go back to 0.3.0?

**Comment by frangio** [comment]
@itinance Can you please open an issue describing your experience? This issue is not about anything breaking, only about the output we produce.

**Comment by itinance** [comment]
Hi @frangio. Before I open a new issue I want to ask you, if there is something wrong in my undesrstanding, how `expectRevert` is assumed to work.

Let's say, I have the following test:

```
    it('reverts if the opening time is in the past', async function () {
      await expectRevert(TokenSale.new(
        (await time.latest()).sub(time.duration.days(1)), closingTime, token.address
      ), 'opening time is in the past');
    });
```

This test expects a `revert`.

But when this `revert` happens, it is printing the following error message:

> Error: Wrong failure type, expected 'opening time is in the past' and got 'Returned error: VM Exception while processing transaction: revert'

Bug or feature? :)

**Comment by nventuro** [comment]
That's indeed how `expectRevert` is used. It is failing because your contract is not reverting with a revert reason, which is why the helper fails (i.e. it didn't receive the reason you provided). It could be that you're triggering a different revert condition, or that your blockchain client doesn't support revert reasons (this happens with older ganache versions -  we do try to detect this though).

Could you:
1) share which version of ganache-cli or ganache-core you're using, and
2) share the code for your smart contract (at least the constructor)?
