### ISSUE TITLE
Using the helpers outside of Truffle (i.e. remove assumption of global web3)

### ISSUE THREAD

**Issue by cnasikas** [OpenZeppelin/openzeppelin-test-helpers#35]
I am trying to `const oz = require('openzeppelin-test-helpers')` but I am getting the following error:

```
/path/to/project/node_modules/openzeppelin-test-helpers/src/setup.js:2
const BN = web3.utils.BN;
           ^

ReferenceError: web3 is not defined
```

Why web3 is not imported inside `setup.js` ? Am I missing something obvious ?

**Comment by cnasikas** [comment]
Oh I see... You assume that we run `truffle test` and web3 is provided by truffle, right ?

**Comment by nventuro** [comment]
Hello @cnasikas, thanks for reporting this!

I've considered supporting a standalone environment  where either the user supplies web3 or `helpers` provides it (since there are so many incompatible versions out there), but there are some extra dependencies on truffle, particularly when it comes to decoding events (though this is something we could do ourselves to decouple that).

Is there any particular reason why you don't want/cannot use truffle? If I'm not mistaken, you can also run `truffle exec` on a script, and it will run with the full truffle environment, providing access to web3, the contract artifacts, etc. (though you will need to set up ganache by yourself, if using a local blockchain).

**Comment by dionyziz** [comment]
@nventuro Thank you for your feedback. I am working with @cnasikas on this grader. We do not want to run it from within a bash script. Rather, our grader runs in a JS environment and we want to capture potential errors from within Javascript, without resorting to using `shell()`-like commands.

**Comment by nventuro** [comment]
@dionyziz my bad for not being clear enough, [`truffle exec` runs a JS script, not bash](https://www.truffleframework.com/docs/truffle/reference/truffle-commands#exec).

**Comment by dionyziz** [comment]
@nventuro I'm not sure how we can use this. This grader is fired up from within a server-side [express](https://expressjs.com) web service which has its own complex environment and is a long-running process behind an nginx. Could you point us to the right direction?

**Comment by frangio** [comment]
We should 100% support using this library outside of a Truffle project.

@nventuro What parts depend on it?

**Comment by cnasikas** [comment]
@nventuro @frangio Thank you for your feedback. I also think that the library should be supported outside Truffle if possible. There are a lot of use cases where the provided functionality by the library is needed. Think of ethernaut for example.

Thanks a lot!

**Comment by nventuro** [comment]
@cnasikas @dionyziz would you expect the helpers to include web3, or for the user to provide it? The first approach has the advantage of us knowing which web3 version we're using, but we'd have to provide a way to set the web3 provider, which is a non-issue in the second one.

@frangio what if the `require` returned a function that receives a web3 instance, and we internally check for its version (`web3.version`)? Usage would look like

```
const { expectEvent, send, shouldFail } = require('openzeppelin-test-helpers')(web3);
```

**Comment by cnasikas** [comment]
@nventuro I think it is better the openzeppelin to provide `web3`, to have fine control on versions, and provide at the same time a way to set the provider.

For example:

```
const oz = require('openzeppelin-test-helpers')
const provider = new oz.web3.providers.WebsocketProvider(provider)
const { expectEvent, send, shouldFail } = oz.init(provider)
```

Reading the code I saw that some modules do not need a provider and depend only on `web-utils`. Maybe that modules can be exported right away without the need of setting a provider.

Thanks a lot for your effort and time putting into this.

**Comment by frangio** [comment]
@cnasikas @dionyziz We've added support for manually injecting a Web3 instance in #38, for situations like yours. It will allow you to write:

```javascript
require('openzeppelin-test-helpers/inject-web3')(web3);
```

Try it out if you'd like and let us know what you think of this!

**Comment by cnasikas** [comment]
@frangio Thanks a lot! That was fast :). I will try it as soon as possible!

**Comment by cnasikas** [comment]
I test it and for the moment everything works fine! Thanks a lot!
