### ISSUE TITLE
Error with node gyp

### ISSUE THREAD

**Issue by ngmachado** [OpenZeppelin/openzeppelin-test-helpers#42]
For the Mac folks with Node install with brew, 

If you are getting an error like "error scrypt@6.0.3 install: `node-gyp rebuild`" when installing with npm, you should try to remove node and install it from the node site.

[link](https://github.com/nodejs/node-gyp/issues/489#issuecomment-77978150)

**Comment by frangio** [comment]
Thanks for the suggestion @ngmachado. I'm closing the issue because there's nothing to do here.
