### ISSUE TITLE
fails to test with the revert reason string with the Ganache GUI v2.0.1

### ISSUE THREAD

**Issue by bebeerd** [OpenZeppelin/openzeppelin-test-helpers#45]
with the Ganache GUI v2.0.1 - which is the latest stable release - `shouldFail.reverting.withMessage` in v0.3.2 or `expectRevert` in master both fails to test the reason string.

Because a regex to test a `nodeInfo` cannot match a **pre-release** or a **meta-data** specified in a semver documentation - https://semver.org/#spec-item-9 and  Ganache GUI v2.0.1 uses ganache-core **v2.5.5-beta.0** - `nodeInfo` is `EthereumJS TestRPC/v2.5.5-beta.0/ethereum-js`

https://github.com/OpenZeppelin/openzeppelin-test-helpers/blob/3eff5bcdda6419d623346ae08899696c7ade8dd2/src/shouldFail.js#L38

https://github.com/OpenZeppelin/openzeppelin-test-helpers/blob/34868ca63d04b820396127a1dea8287a1c901629/src/expectRevert.js#L29

expectRevert output:

    openzeppelin-test-helpers WARN       expectRevert: revert reason checking only supported on Ganache v2.2.0 or newer.

**Comment by frangio** [comment]
Thanks for reporting @bebeerd! There's a fix for this in #46. Would you mind testing it?

**Comment by bebeerd** [comment]
@frangio It's working now 👍
