### ISSUE TITLE
Feature request: specify units in get and delta methods of balance tracker

### ISSUE THREAD

**Issue by tinchoabbate** [OpenZeppelin/openzeppelin-test-helpers#57]
I've found myself many times, while using the ETH balance trackers, having to do:
~~~
web3.utils.fromWei(await ethBalanceTracker.delta())
~~~
It would be far more natural if we just could tell the balance tracker the units in which we want the returned data. Something like:
~~~
await ethBalanceTracker.delta({units: 'ether'})
~~~
or even:
~~~
await ethBalanceTracker.delta('ether')
~~~
Same goes for the `get` method of the tracker.
I think this would make the tests far cleaner and elegant. WDYT ?

Thankssss!

**Comment by frangio** [comment]
Sounds like a good idea!

What do you think about specifying the unit in the tracker instantiation? Would this work for your use case?

```javascript
const balanceTracker = await balance.tracker(account, 'ether');
// ...
await balanceTracker.delta();
```

**Comment by tinchoabbate** [comment]
For my specific use case (just logging stuff in ETH units instead of Wei), what you suggest would work perfect :raised_hands: 

However, I feel that being able to specify the units in `get` or `delta` would give devs a bit more flexibility if for some reason they need to log data using different units in the same test. But maybe that's just an extreme case, in which using `web3` directly would make sense.
