### ISSUE TITLE
truffle-contract@4.0.26 seems to break web3 dependencies.

### ISSUE THREAD

**Issue by ccolorado** [OpenZeppelin/openzeppelin-test-helpers#62]
```javascript
const { BN, constants, expectEvent, expectRevert, time } = require('openzeppelin-test-helpers/configure');
```

Rises the following error:

`Error: Error: web3@1.2.0 detected, incompatible with requirement of web3@1.0.0-beta.37`

Seems that truffle-contract@4.0.26 is forcing web3 to bump to version 1.2.

**Comment by nventuro** [comment]
Thanks for raising this @ccolorado! We should also update to 1.2 now that it's come out and remove that check, probably in a v0.5.0 release.

**Comment by fodisi** [comment]
I'm facing the same issue here. Thanks for addressing it.
Is there any available workaround? Should I downgrade my truffle version?
This is are my configs:

Truffle v5.0.29 (core: 5.0.29)
Solidity v0.5.0 (solc-js)
Node v10.16.0
Web3.js v^1.2.0

**Comment by ccolorado** [comment]
@nventuro awesome, thanks for this timely fix.
