### ISSUE TITLE
+ expected - actual in expectRevert

### ISSUE THREAD

**Issue by ilanolkies** [OpenZeppelin/openzeppelin-test-helpers#68]
The output of an `expectRevert` test may be more helpful if it included the expect-revert model of any other test.

Actual message is just
```
AssertionError: Wrong kind of exception received
      at expectException (node_modules/openzeppelin-test-helpers/src/expectRevert.js:13:14)
      at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by abcoathup** [comment]
Hi @ilanolkies 
Thanks for raising.  This issue duplicates: https://github.com/OpenZeppelin/openzeppelin-test-helpers/issues/66 with an associated PR: https://github.com/OpenZeppelin/openzeppelin-test-helpers/pull/67

**Comment by nventuro** [comment]
Closing as duplicate.
