### ISSUE TITLE
@truffle/contract is not available due to Truffle bundling

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-test-helpers#81]
In #75 we assumed that in a Truffle environment the package `@truffle/contract` would be available to require, but it turns out that since Truffle bundles all of its dependencies this is not true.

Temporarily, we will add `@truffle/contract` as a dependency of test-helpers, but this _may_ cause issues since it will be a different version than the Truffle environment where we're running.

Alternatively, we can use the global `artifacts` object and run `artifacts.require` but we haven't looked into this in detail and don't know if it will work.

**Comment by nventuro** [comment]
`@truffle/contract` was added as a dependency and used directly in b5ceeff2fd63bae02e944a734e7706648f4964c1. The only concern is that incompatible versions of it may exist (I'm not aware of this being the case).

**Comment by nventuro** [comment]
`artifacts.required` could not be used. Apparently there is support for loading artifacts from NPM packages with a `<package>/<contract>` syntax, but it is broken since it looks in a `/tmp` directory where `node_modules` is not copied to.
