### ISSUE TITLE
"Global" web3 and artifacts not available in Truffle migrations

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-test-helpers#82]
For some reason there are global-looking `web3` and `artifacts` variables in a Truffle migration, but these are not accessible from required modules, nor do they show up in the `globals` object. Truffle must be injecting them in some other way.

This breaks our ability to detect a Truffle environment or even use the global `web3` object to automatically get the current provider. I don't see an easy way out of this. We should document that in migrations people will have to manually configure the provider.

We might have to make `artifacts` configurable too.

**Comment by frangio** [comment]
Given this, we might want to bring back the `web3` option to `configure` so that configuring the library for Truffle migrations is a bit nicer:

```javascript
require('@openzeppelin/test-helpers/configure')({ web3, artifacts });
```

As opposed to:
```javascript
require('@openzeppelin/test-helpers/configure')({ provider: web3.currentProvider, artifacts });
```

**Comment by nventuro** [comment]
`artifacts` cannot be used anyway (see https://github.com/OpenZeppelin/openzeppelin-test-helpers/issues/81), so we decided to keep `provider` and configure truffle environments explicitly with `environment: 'truffle'`
