### ISSUE TITLE
Zero bytes32 constant

### ISSUE THREAD

**Issue by ilanolkies** [OpenZeppelin/openzeppelin-test-helpers#91]
https://github.com/OpenZeppelin/openzeppelin-test-helpers/blob/9d06cc93f05d8366f97b0163183b284e21b6c590/src/constants.js#L4

Hi! A _zero bytes32_ constant would be very useful!
Thanks.

**Comment by nventuro** [comment]
Hello @ilanolkies, thanks for your interest in the test helpers!

Can you share an example of when you'd use such a constant? I don't think I've encountered situations where I need to test against a 32-byte constant.

**Comment by ilanolkies** [comment]
Yes, of course! It’s usually used to identify the root of a tree structure. For example, to find ENS root node you query `ens.owner(‘0x00...00’)`
