### ISSUE TITLE
expectEvent does not return the event object

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-test-helpers#93]
In some cases, event parameters need to be manually tested (e.g. because a value is only checked to be in a range as opposed to being exactly equal to another one). To support these scenarios, `expectEvent` should return an object with the event, so that these values can then be extracted  and tested manually:

```javascript
const event = expectEvent(receipt, 'MyEvent');
expect(event.args.param).to.be.greaterThan(50);
```

Since we're both supporting web3 and truffle workflows, which have different event formats in their receipts, it is not clear what format the returned object should have. In particular, there's a difference in how numbers are handled: truffle returns `BN` instances, while web3 uses regular strings.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-test-helpers/pull/129.
